# Inspired by: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id:
          check-byte-order-marker # Forbid UTF-8 byte-order markers
          # Check for files with names that would conflict on a case-insensitive
          # filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
      - id: check-json
      - id:
          check-ast # Is it valid Python?
          # Check for debugger imports and py37+ breakpoint() calls
          # in python source.
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v0.950
  #     hooks:
  #     -   id: mypy
  #         # args: [--ignore-missing-imports]
  #         args: [--disable-error-code=misc]
  - repo: https://github.com/pycqa/pylint
    rev: v2.13.8
    hooks:
      - id: pylint
  # -   repo: https://github.com/ambv/black
  #     rev: 22.3.0
  #     hooks:
  #     - id: black
  #       language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: tests/serverless_architecture/functions/api
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.74.1 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: 'serverless_architecture/.*template\.yaml'
        exclude: "serverless_architecture/containers/ops/batch-jobs/template.yaml"
        args:
          - --ignore-checks=W3002,W3005
